### ISSUE TITLE
Syntax error in R3 System

### ISSUE THREAD

**Issue by Jules1337dev** [stockbal/abap-code-search-tools#4]
Hi Ludwig,

first: thanks for the great plugins and the effort you put in.
I have an issue regarding the abap code search plugin. After installing the backend and the plugin the following error occured:
![image](https://user-images.githubusercontent.com/84089388/217167264-870dead6-a20d-4e9e-a084-60916c2542fc.png)
![image](https://user-images.githubusercontent.com/84089388/217167449-4e07204a-dff5-4558-8a61-79fdd80380f7.png)

I think using offset is not possible in R3.

Maybe you can fix this or provide one branch for R3 and one for S4?

Thank in advance
Julian

**Comment by stockbal** [comment]
Hi Julian,

the plug-in is compatible with R3. But the minimum requirement is NW 7.40 SP08.
![image](https://user-images.githubusercontent.com/35834861/217178135-7a3fa8a8-14dc-457d-8bcb-b7f9ac3053d7.png)

Currently it is not planned from my side to release a version that is compatible with a lower SP on 7.40 or even a version compatible with < 7.40.

Best regards,
Ludwig

**Comment by Jules1337dev** [comment]
Hi Ludwig, 

ahh we got 7.50 but SP only 0025.
Sorry, my bad.

Best regards,
Julian

**Comment by stockbal** [comment]
Hm...
I would have thought that 7.50 would have all changes of 7.40 SP08
![image](https://user-images.githubusercontent.com/35834861/217275730-ac881480-c3e6-4fe9-ad83-7ec32f134e8d.png)

I have the Code Search installed and running on another system with 7.50 SP18

**Comment by Jules1337dev** [comment]
Hi Ludwig,

i asked our basis team internally. The following answer was received:

With the next kernel patch all 7.40 and 7.50 will get the bug, see sap note 3279914: 
https://launchpad.support.sap.com/#/notes/3279914/D.

Can you possibly rebuild it?

Maybe you can use the coding in the note:
The "SELECT .... INTO TABLE @itab LIMIT @limit@ OFFSET @offset." can be simulated like this:

OPEN CURSOR @<cursor> FOR SELECT ....

FETCH NEXT CURSOR @<cursor> INTO TABLE @itab PACKAGE SIZE @offset.

if offset < lines( itab ). 

  FETCH NEXT CURSOR @<cursor> INTO TABLE @itab PACKAGE SIZE @limit.

else.

  clear itab. "offset >= lines( itab ) means nothing found.

endif.

Best regards,
Julian

**Comment by stockbal** [comment]
Hi Julian,

I am not sure SAP knows how the OPEN/FETCH CURSOR clause is working. Or at least not the person who added this workaround in the note. This approach would never return any data in my case and the search would run endlessly without ever returning any data.

I think the best/only solution would be to implement the SELECT in native SQL for NW < 7.51. 
Could you tell me the DB you are using on your ABAP system, then I would try to implement a solution that works with that one first.

BR
Ludwig

**Comment by Jules1337dev** [comment]
Hi Ludwig,

i haven´t used the OPEN/FETCH CURSOR clause yet. Feel free to fix it the way you want :)

We are using an oracle database based on release 19.6.0.0.0. 
Do you need any further information?

Thanks for your effort.

Best regards,
Julian

**Comment by stockbal** [comment]
I am not sure how the chances are that SAP only added a syntax check for the `OFFSET` clause, but in a dynamic context it would still work.  
But maybe you could check on your system if the following code snippet would run successfully or not 😊.

```abap
DATA: source_lines   TYPE TABLE OF string,
      temp_prog_name TYPE progname.

source_lines = VALUE #(
( |REPORT z_open_sql_offset_test.| )
( || )
( |FORM run_select.| )
( | SELECT obj_name| )
( |   FROM tadir| )
( |   ORDER BY obj_name| )
( |   INTO TABLE @DATA(result)| )
( |   OFFSET 20| )
( |   UP TO 10 ROWS.| )
( || )
( | cl_demo_output=>display_data( result ).| )
( |ENDFORM.| )
).

GENERATE SUBROUTINE POOL source_lines
  NAME temp_prog_name
  MESSAGE DATA(message).

IF temp_prog_name IS NOT INITIAL.
  PERFORM ('RUN_SELECT') IN PROGRAM (temp_prog_name) IF FOUND.
ENDIF.
```

**Comment by Jules1337dev** [comment]
Unfortunately it didn't work :/ The same error occurs when calling the offset statement dynamically

![dynamicOffsetCall](https://user-images.githubusercontent.com/84089388/218347481-112845e0-ff75-4238-a02b-4e24b911fc5b.png)

**Comment by stockbal** [comment]
Ok, too bad. Then I will go ahead and try to build a first solution for Oracle DB. 

BR,
Ludwig

**Comment by stockbal** [comment]
I just created a solution that works with Oracle DB. I tested it on our 7.40 with the following parameters:
![image](https://user-images.githubusercontent.com/35834861/218860948-610d6e82-e413-457d-8a16-663ad70ecc46.png)

You can test it by pulling the branch `nw-740`

**Comment by Jules1337dev** [comment]
Thanks for the quick fix/response.
These are my specs 

![image](https://user-images.githubusercontent.com/84089388/218951012-ef3c6269-adcc-46a3-89a1-fc8b11be7a35.png)

Unfortunately when i try to pull the branch nw-740 the following dump occurs:
![image](https://user-images.githubusercontent.com/84089388/218951276-fe668d01-788d-44e8-9b9e-029b02610caf.png)
![image](https://user-images.githubusercontent.com/84089388/218951327-0ec4663a-15d4-4264-b462-5313ac319026.png)

**Comment by stockbal** [comment]
An update to abapGit should solve the problem.
If you experience dumps during the update of abapGit, you may have to first
update the standalone version of abapGit (zabapgit_standalone) and then
start this report to update the development version of abapGit.
After that the pull should work without problems

**Comment by Jules1337dev** [comment]
Hi Ludwig, 

i realized it myself and updated the abapGit. Now the pull works. 
when trying to search code following message occurs:

![image](https://user-images.githubusercontent.com/84089388/218998734-76fe34cc-c694-45d9-84f2-a4719c3f0594.png)
![image](https://user-images.githubusercontent.com/84089388/218998844-20d399c0-2968-4e18-b0ae-30a3c994d4f3.png)

Thanks for your support

**Comment by Jules1337dev** [comment]
I had to activate some inactive objects but then it works! 
Great!
:)

**Comment by stockbal** [comment]
Ok, great.
If the issue with the transformation ZADCOSET_SEARCH_SCOPE_PARAMS persists, please open a new issue.

BR,
Ludwig

**Comment by Jules1337dev** [comment]
Yes, I will do that, but I don't think so. The class was inactive, so I think the new version will run

**Comment by Jules1337dev** [comment]
I have one last question:
It affects the code search only indirectly. I´ve also installed the abap tags plugin and it works fine.

Why can´t i use the Tags within the Code Search?
![image](https://user-images.githubusercontent.com/84089388/219003979-ce68041b-9c23-4155-8abc-8bfb7c12f4be.png)

I believe i was able to select tags here when pulling the main branch.

**Comment by stockbal** [comment]
It is described in the included Eclipse Help for the Code Search Plug-in 
![image](https://user-images.githubusercontent.com/35834861/219006596-b29155d5-baeb-46fc-a7d2-9d8e263877f4.png)

> The Tags section is only available if the [ABAP Tags](https://marketplace.eclipse.org/content/abap-tags) plugin is installed and if the [ABAP Tags backend](https://github.com/stockbal/abap-tags-backend) is available in the selectedABAP project.

**Comment by Jules1337dev** [comment]
Regarding your previous post, i got the backend and the plugin otherwise the "usual" tag search won´t work

**Comment by Jules1337dev** [comment]
Hm, okay. I set a breakpoint one the first statement in this method, but the debugger do not stop when pressing STRG + H

**Comment by Jules1337dev** [comment]
Well okay I restarted eclipse and now it works. I just do not ask any questions :D

**Comment by stockbal** [comment]
Check this setting please:
![image](https://user-images.githubusercontent.com/35834861/219009429-397ddf7e-47f1-40b7-b033-dbfb738608c9.png)

It could also be that you have to debug it via SAP GUI if eclipse blocks it

**Comment by Jules1337dev** [comment]
You´re right this setting was not set. But now that it works, it fits for me
Thank you!
